[plugins]
android-application = { id = "com.android.application", version = "8.1.1" }
secrets-gradle-plugin = { id = "com.google.secrets_gradle_plugin", version = "0.5" }

[versions]
constraintlayout = "2.2.1"
appcompat = "1.6.1"
material = "1.9.0"
activity = "1.7.2"
play-services-maps = "18.1.0"
junit = "4.13.2"
ext-junit = "1.1.5"
espresso-core = "3.5.1"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "play-services-maps" }
junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "ext-junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
